FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Storage/Storage.csproj", "Storage/"]
RUN dotnet restore "Storage/Storage.csproj"

COPY . .
WORKDIR "/src/Storage"
RUN dotnet build "Storage.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "Storage.dll"]