export enum AppTags {
  html = 'HTML',
  css = 'CSS',
  js = 'JavaScript',
  ts = 'TypeScript',
  bootstrap = 'Bootstrap',
  angular = 'Angular',
  aspnet = 'ASP.NET Core',
  ef = 'EF Core',
  mysql = 'MySQL',
  mssql = 'MSSQL',
  cs = 'C#',
  wpf = 'WPF',
  winforms = 'Win Forms',
  cpp = 'C++',
  bash = 'Bash',
  arduino = 'Arduino',
  iot = 'IoT',
  pcb = 'PCB',
  dedicated = 'Dedicated',
  cloud = 'Cloud',
}
