FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000
EXPOSE 5001

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Services/Messanger/Messanger.csproj", "Services/Messanger/"]

RUN dotnet restore "Services/Messanger/Messanger.csproj"

COPY . .
WORKDIR "/src/Services/Messanger"
RUN dotnet build "Messanger.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "Messanger.dll"]