FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Services/Portfolio/Portfolio.csproj", "Services/Portfolio/"]

RUN dotnet restore "Services/Portfolio/Portfolio.csproj"

COPY . .
WORKDIR "/src/Services/Portfolio"
RUN dotnet build "Portfolio.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "Portfolio.dll"]