FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000
EXPOSE 5001

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Services/Pricing/Pricing.csproj", "Services/Pricing/"]

RUN dotnet restore "Services/Pricing/Pricing.csproj"

COPY . .
WORKDIR "/src/Services/Pricing"
RUN dotnet build "Pricing.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "Pricing.dll"]