FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Services/IdentityServer/IdentityServer.csproj", "Services/IdentityServer/"]

RUN dotnet restore "Services/IdentityServer/IdentityServer.csproj"

COPY . .
WORKDIR "/src/Services/IdentityServer"
RUN dotnet build "IdentityServer.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "IdentityServer.dll"]