FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["Services/Users/Users.csproj", "Services/Users/"]

RUN dotnet restore "Services/Users/Users.csproj"

COPY . .
WORKDIR "/src/Services/Users"
RUN dotnet build "Users.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "Users.dll"]