FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000

ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /src
COPY ["ApiGateways/OcelotApiGateway/OcelotApiGateway.csproj", "ApiGateways/OcelotApiGateway/"]

RUN dotnet restore "ApiGateways/OcelotApiGateway/OcelotApiGateway.csproj"

COPY . .
WORKDIR "/src/ApiGateways/OcelotApiGateway"
RUN dotnet build "OcelotApiGateway.csproj" -c $BUILD_CONFIGURATION -o /app

WORKDIR "/app"
ENTRYPOINT ["dotnet", "OcelotApiGateway.dll"]