export enum AppRoutes {
  DASHBOARD = 'dashboard',

  DASHBOARD_MAIN = 'main',
  DASHBOARD_MAIN_PORTFOLIO = 'portfolio',
  DASHBOARD_MAIN_PORTFOLIO_PROJECTS = 'projects',
  DASHBOARD_MAIN_PORTFOLIO_TAGS = 'tags',
  DASHBOARD_MAIN_PORTFOLIO_TOP_PROJECTS = 'top-projects',
  DASHBOARD_MAIN_PORTFOLIO_SETUP_PROJECT_WIZARD = 'setup-project-wizard',
  DASHBOARD_MAIN_SERVICES = 'services',

  DASHBOARD_NOTIFICATIONS = 'notifications',
  DASHBOARD_NOTIFICATIONS_MESSAGES = 'messages',
  DASHBOARD_NOTIFICATIONS_MESSAGES_MESSAGE = 'message',

  DASHBOARD_USERS = 'users',
  DASHBOARD_USERS_ADMINS = 'admins',
}
