version: '3.4'

services:
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
      - ConnectionStrings__IdentityDb=Server=db;Database=DavidStudio.Service.IdentityDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - IdentityWebSpa=http://localhost:44200
      - SpaClient=http://localhost:4200
    ports:
      - "5010:5000"
      - "5011:5001"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db

  identity-server-web:
    ports:
      - "44200:80"
    depends_on:
      - identity-server

  portfolio-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PortfolioDb=Server=db;Database=DavidStudio.Service.Portfolio;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Services__StorageUri=http://storage-api:5009
    ports:
      - "5030:5000"
    depends_on:
      - db

  storage-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__StorageDb=Server=db;Database=DavidStudio.Service.Storage;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Kestrel__Endpoints__Http__Url=http://0.0.0.0:5000
      - Kestrel__Endpoints__Http__Protocols=Http1AndHttp2
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:5009
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - Resources_Url=http://localhost:5050/Resources
      - StorageOptions__StoragePath=/storage
    volumes:
        - storage:/storage
    ports:
      - "5050:5000"
      - "5059:5009"
    depends_on:
      - db

  db:
    env_file:
      - .env
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqldata:/var/opt/mssql

  rabbitmq:
    env_file:
      - .env
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - mqdata:/var/lib/rabbitmq/
        - mqlogs:/var/log/rabbitmq

volumes:
  storage:
  sqldata:
  mqdata:
  mqlogs: