version: '3.4'

services:
  web-api-gw:
    image: ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile.develop

  identity-server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/IdentityServer/Dockerfile.develop

  identity-server-client:
    image: ${DOCKER_REGISTRY-}identityserverclient
    build:
      context: .
      dockerfile: Services/IdentityServer/ClientApp/Dockerfile.develop

  users-api:
    image: ${DOCKER_REGISTRY-}users
    build:
      context: .
      dockerfile: Services/Users/Dockerfile.develop

  portfolio-api:
    image: ${DOCKER_REGISTRY-}portfolio
    build:
      context: .
      dockerfile: Services/Portfolio/Dockerfile.develop

  pricing-api:
    image: ${DOCKER_REGISTRY-}pricing
    build:
      context: .
      dockerfile: Services/Pricing/Dockerfile.develop

  storage-api:
    image: ${DOCKER_REGISTRY-}storage
    build:
      context: .
      dockerfile: Services/Storage/Dockerfile.develop

  messenger-api:
    image: ${DOCKER_REGISTRY-}messenger
    build:
      context: .
      dockerfile: Services/Messanger/Dockerfile.develop

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  rabbitmq:
    image: rabbitmq:3-management