version: '3.4'

services:
  db:
    env_file:
      - .env
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqldata:/var/opt/mssql
        
volumes:
  sqldata: