version: '3.4'

services:
  web-api-gw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - IdentityUrl=http://identity-server:5000
    ports:
      - "8080:5000"
    volumes:
      - ./ApiGateways/Web.Bff:/app/configuration

  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
      - ConnectionStrings__IdentityDb=Server=db;Database=DavidStudio.Service.IdentityDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - IdentityServer=https://localhost:5011
      - IdentityWebSpa=https://localhost:44300
      - SpaClient=https://localhost:4200
      - UsersApiClient=http://localhost:5020
      - PortfolioApiClient=http://localhost:5030
      - PricingApiClient=http://localhost:5040
      - StorageApiClient=http://localhost:5070
      - MessengerApiClient=http://localhost:5080
    ports:
      - "5010:5000"
      - "5011:5001"
    volumes:
      - ../certs:/https:ro
    depends_on:
      - db
      - rabbitmq

  identity-server-client:
    ports:
      - "44300:443"
    volumes:
      - ../certs:/https:ro
    depends_on:
      - identity-server

  users-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Services__IdentityServerGrpcUri=http://identity-server:5005
      - Identity__Url=http://identity-server:5000
      - Identity__ExternalUrl=http://localhost:5010
    ports:
      - "5020:5000"
    depends_on:
      - rabbitmq

  portfolio-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PortfolioDb=Server=db;Database=DavidStudio.Service.Portfolio;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Services__StorageUri=http://storage-api:5009
      - Identity__Url=http://identity-server:5000
      - Identity__ExternalUrl=http://localhost:5010
    ports:
      - "5030:5000"
    depends_on:
      - db
      - rabbitmq

  pricing-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PricingDb=Server=db;Database=DavidStudio.Service.PricingDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - Identity__Url=http://identity-server:5000
      - Identity__ExternalUrl=http://localhost:5010
    ports:
      - "5040:5000"
    depends_on:
      - db

  storage-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__StorageDb=Server=db;Database=DavidStudio.Service.Storage;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Resources_Url=http://localhost:5070/Resources
      - StorageOptions__StoragePath=/storage
      - Identity__Url=http://identity-server:5000
      - Identity__ExternalUrl=http://localhost:5010
    volumes:
        - storage:/storage
    ports:
      - "5070:5000"
      - "5079:5009"
    depends_on:
      - db
      - rabbitmq

  messenger-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__MessagesDb=Server=db;Database=DavidStudio.Service.MessagesDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__EventBus=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${EXTERNAL_HOST}:5672/
      - Identity__Url=http://identity-server:5000
      - Identity__ExternalUrl=http://localhost:5010
    ports:
      - "5080:5000"
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - $HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets
    depends_on:
      - db
      - rabbitmq

  db:
    env_file:
      - .env
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqldata:/var/opt/mssql

  rabbitmq:
    env_file:
      - .env
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - mqdata:/var/lib/rabbitmq/
        - mqlogs:/var/log/rabbitmq

volumes:
  storage:
  sqldata:
  mqdata:
  mqlogs: