version: '3.4'

services:
  # identity-server:
  #   image: ${DOCKER_REGISTRY-}identityserver
  #   build:
  #     context: .
  #     dockerfile: Services/IdentityServer/Dockerfile.develop

  # users-api:
  #   image: ${DOCKER_REGISTRY-}users
  #   build:
  #     context: .
  #     dockerfile: Services/Users/Dockerfile.develop

  # portfolio-api:
  #   image: ${DOCKER_REGISTRY-}portfolio
  #   build:
  #     context: .
  #     dockerfile: Services/Portfolio/Dockerfile.develop

  # storage-api:
  #   image: ${DOCKER_REGISTRY-}storage
  #   build:
  #     context: .
  #     dockerfile: Services/Storage/Dockerfile.develop

  messanger:
    image: ${DOCKER_REGISTRY-}messagner
    build:
      context: .
      dockerfile: Services/Messanger/Dockerfile.develop

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  rabbitmq:
    image: rabbitmq:3-management