version: '3.4'

services:
  identity-server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile.develop

  users-api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users/Dockerfile.develop

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"