version: '3.4'

services:
#  identity-server:
#    image: ${DOCKER_REGISTRY-}identityserver
#    build:
#      context: .
#      dockerfile: IdentityServer/Dockerfile.develop
#
#  users-api:
#    image: ${DOCKER_REGISTRY-}usersapi
#    build:
#      context: .
#      dockerfile: Users/Dockerfile.develop

  portfolio-api:
    image: ${DOCKER_REGISTRY-}portfolio
    build:
      context: .
      dockerfile: Services/Portfolio/Dockerfile.develop

  storage-api:
    image: ${DOCKER_REGISTRY-}storage
    build:
      context: .
      dockerfile: Services/Storage/Dockerfile.develop

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  rabbitmq:
    image: rabbitmq:3-management